
# Define gradient boosting learner parameter set ----
gb_ps <- ParamHelpers::makeParamSet(
  ParamHelpers::makeDiscreteParam("booster",
                                  values = c("gbtree")),
  ParamHelpers::makeNumericParam("eta",
                                 lower = 0,
                                 upper = 1,
                                 trafo = function(x) x/1e4,
                                 requires = quote(booster %in% c("gbtree"))),
  ParamHelpers::makeNumericParam("gamma",
                                 lower = 0,
                                 upper = 10,
                                 requires = quote(booster %in% c("gbtree"))),
  ParamHelpers::makeIntegerParam("max_depth",
                                 lower = 1L,
                                 upper = 14L,
                                 requires = quote(booster %in% c("gbtree"))),
  ParamHelpers::makeNumericParam("min_child_weight",
                                 lower = 0L,
                                 upper = 7L,
                                 trafo = function(x) 2^{x},
                                 requires = quote(booster %in% c("gbtree"))),
  ParamHelpers::makeNumericParam("subsample",
                                 lower = 0,
                                 upper = 1,
                                 requires = quote(booster %in% c("gbtree"))),
  ParamHelpers::makeNumericParam("colsample_bytree",
                                 lower = 0,
                                 upper = 1,
                                 requires = quote(booster %in% c("gbtree"))),
  ParamHelpers::makeNumericParam("colsample_bylevel",
                                 lower = 0,
                                 upper = 1,
                                 requires = quote(booster %in% c("gbtree"))),
  ParamHelpers::makeNumericParam("lambda",
                                 lower = -10,
                                 upper = 10,
                                 trafo = function(x) 2^{x},
                                 requires = quote(booster %in% c("gblinear"))),
  ParamHelpers::makeNumericParam("lambda_bias",
                                 lower = 0,
                                 upper = 1e5,
                                 trafo = function(x) x/1e4,
                                 requires = quote(booster %in% c("gblinear"))),
  ParamHelpers::makeNumericParam("alpha",
                                 lower = 0,
                                 upper = 1e5,
                                 trafo = function(x) x/1e4,
                                 requires = quote(booster %in% c("gblinear"))),
  ParamHelpers::makeNumericParam("base_score",
                                 lower = 0,
                                 upper = 1),
  ParamHelpers::makeIntegerParam("nrounds",
                                 lower = 1L,
                                 upper = 5000L)
)
