
# Define SVM learner parameter set ----
svm_ps <- ParamHelpers::makeParamSet(
  ParamHelpers::makeDiscreteParam("type",
                                  values = c("C-svc", "nu-svc")),
  ParamHelpers::makeNumericParam("C",
                                 lower = -5,
                                 upper = 5,
                                 trafo = function(x) 10^{x},
                                 requires = quote(type %in% c("C-svc", "C-bsvc"))),
  ParamHelpers::makeNumericParam("nu",
                                 lower = 0,
                                 upper = 1,
                                 requires = quote(type == "nu-svc")),
  ParamHelpers::makeDiscreteParam("kernel", values = c("rbfdot",
                                                       "vanilladot",
                                                       "polydot",
                                                       "laplacedot",
                                                       "besseldot")),
  ParamHelpers::makeNumericParam("sigma",
                                 lower = -5,
                                 upper = 2,
                                 trafo = function(x) 10^{x},
                                 requires = quote(kernel %in% c("rbfdot",
                                                                "laplacedot",
                                                                "besseldot"))),
  ParamHelpers::makeIntegerParam("degree",
                                 lower = 1L,
                                 upper = 5L,
                                 requires = quote(kernel %in% c("polydot",
                                                                "besseldot"))),
  ParamHelpers::makeNumericParam("scale",
                                 lower = -5,
                                 upper = 5,
                                 trafo = function(x) 10^{x},
                                 requires = quote(kernel %in% c("polydot"))),
  ParamHelpers::makeNumericParam("offset",
                                 lower = -3,
                                 upper = 3,
                                 trafo = function(x) 2^{x},
                                 requires = quote(kernel %in% c("polydot"))),
  ParamHelpers::makeIntegerParam("order",
                                 lower = 0L,
                                 upper = 6L,
                                 requires = quote(kernel == "besseldot"))
)
